//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSelect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public int ModelId { get; set; }
        public int BodyTypeId { get; set; }
        public int FuelTypeId { get; set; }
        public string Color { get; set; }
        public decimal EngineVolume { get; set; }
        public int ReleaseYear { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual BodyType BodyType { get; set; }
        public virtual FuelType FuelType { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
