//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSelect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int CarId { get; set; }
        public int TariffId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ConsultantId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Description { get; set; }
        public Nullable<int> FuelTypeId { get; set; }
        public Nullable<int> GBTypeId { get; set; }
        public Nullable<int> BodyTypeId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> DriveTypeId { get; set; }
        public Nullable<int> Milleage { get; set; }
    
        public virtual BodyType BodyType { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
        public virtual DriveType DriveType { get; set; }
        public virtual FuelType FuelType { get; set; }
        public virtual GBType GBType { get; set; }
        public virtual Model Model { get; set; }
        public virtual State State { get; set; }
        public virtual Tariff Tariff { get; set; }
        public virtual User User { get; set; }
    }
}
